on: [push]

name: self-hosted-example

jobs:
  simpleExample:
    runs-on: self-hosted
    steps:
    # checkout branch
    - uses: actions/checkout@main

    #- name: Get ReadyAPI
    #  run: curl https://dl.eviware.com/ready-api/3.40.1.0/ReadyAPI-x64-3.40.1.exe -o ~/ReadyAPI-x64-3.40.1.exe
      
    - name: Get Install ReadyAPI
      run: echo "install ReadyAPI"
    
   # - name: Test 1
   #   working-directory: C:\Work
   #   run: ./rapi-test.bat
      
    - name: Test 2
      working-directory: C:\Program Files\SmartBear\ReadyAPI-3.40.1\bin\
      run: cmd /c "testrunner.bat -r -a -j -f${WORKSPACE} "-RJUnit-Style HTML Report" -FXML "-EDefault environment" "C:\Work\CalcSoap-readyapi-project.xml""

